export { default as ourWorksImg1 } from "/ourWorks/1.webp";
export { default as ourWorksImg2 } from "/ourWorks/2.webp";
export { default as ourWorksImg3 } from "/ourWorks/3.webp";
export { default as ourWorksImg4 } from "/ourWorks/4.webp";
export { default as ourWorksImg5 } from "/ourWorks/5.webp";
export { default as ourWorksImg6 } from "/ourWorks/6.webp";
export { default as ourWorksImg7 } from "/ourWorks/7.webp";
export { default as ourWorksImg8 } from "/ourWorks/8.webp";
export { default as ourWorksImg9 } from "/ourWorks/9.webp";
